### ISSUE TITLE
 License infringement

### ISSUE THREAD

**Issue by xafero** [fizzed/blaze#1]
Your repository "blaze-kotlin" project is violating my rights as a developer to use the AGPL license. 
At least one class of it - if not the whole - has been (at least initially) taken from my repository (https://github.com/xafero/dynkt) and then it has been illegally sublicensed under the terms of the ASL2!

**Comment by jjlauer** [comment]
@xafero I'm actually pretty careful about this stuff, so I reviewed your claim tonight.  Yes, it does look like I borrowed some lines of code for compiling a kotlin file from your project (in KotlinCompiler.java). No, everything else in blaze and blaze-kotlin is my own work that I spent quite a bit of time on and its a bold claim to make some sort of leap that the entire concept of compiling kotlin is your idea.  I know I used numerous unit tests from kotlin itself to figure out how to get it to work for my needs.  I have no goal of being a JSR 232 engine for Kotlin -- and it doesn't even work with the latest kotlin. I'm happy to rewrite the few lines of code and/or add an attribution at the top.

I was curious about your own work though since you seem on top of this. Your https://github.com/xafero/dynjc project says its based on https://java.net/projects/scripting/sources/svn/show/trunk/engines/java which uses the Sun Micro license and actually you're probably violating their terms by relicensing it as AGPL.  I could make the same claim as you did with mine, but if we're both reasonable folks we both know its somewhat trivial in the grand scheme of things.

**Comment by xafero** [comment]
Just for clarification: 
* It is already a violation regardless of the amount of code (Oracle sues Google for 37 files - where is the line here?)
* I did not "boldly claim" something about the "entire concept", that's nonsense
* The code _included_ the library I developed as if it were LGPL ...!
* My intention by figuring out how to use Kotlin was to give something to the community, not to work for a company or some person copying my code and therefore knowledge - although maybe _later_ they are changing enough

Could you swear that you never:
* looked at any line of a project which license you don't agree with ("No, everything else in blaze")
* ignore someone's rights because you think it's "somewhat trivial"
?

**Comment by jjlauer** [comment]
@xafero I already had a "feature_kotlin1" branch for supporting Kotlin v1 final that I started last month.  Just finished it up and merged it in.  New code is 100% based on Kotlin unit tests -- and Kotlin is apache licensed, btw.

**Comment by xafero** [comment]
The 'invalid' is not nice, and it's possible to sublicense; just inform yourself: http://www.apache.org/licenses/GPL-compatibility.html
